# Generated by Django 4.0.3 on 2022-03-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
